# Generated by Django 3.0.6 on 2021-01-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earning',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
