# Generated by Django 3.0.6 on 2021-01-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20210108_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earning',
            old_name='date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='date',
            new_name='create_date',
        ),
    ]
